Repository kickstartDS/kickstartDS, pull requests merged in 2023-04, with the labels that each got.

#1272 Fix broken links on layouts overview page
  packages/tools/docusaurus/docs/foundations/layout/index.mdx
  yarn.lock
Labels: documentation

#1274 Fix text-media intext media alignment
  packages/components/base/source/text-media/text-media.scss
Labels: patch

#1275 Add missing object types to schemas
  packages/components/blog/source/post-share-bar/post-share-bar.schema.json
Labels: patch

#1250 split style-dictionary scripts
  packages/tools/style-dictionary/createTokens.js
  packages/tools/style-dictionary/index.js
  packages/tools/style-dictionary/writeTokens.js
Labels: patch

#1277 fix babel targets
  packages/tools/bundler/bundle/bundleTs.js
  packages/tools/bundler/bundle/rollupUtils.js
  yarn.lock
Labels: patch

#1279 run ci jobs on dependabot branches
  .circleci/config.yml
  .github/dependabot.yml
Labels: internal

#1299 Simplify section headline referencing
  packages/components/base/source/section/section.schema.json
Labels: patch

#1302 Update internal dependencies
  packages/components/base/package.json
  packages/components/blog/package.json
  packages/components/core/package.json
  packages/components/form/package.json
  yarn.lock
Labels: patch
