Repository kickstartDS/kickstartDS, pull requests merged in 2023-11, with the labels that each got.

#1518 Stop merging allOfs in component TypeScript type generation
  packages/components/base/source/button/ButtonProps.ts
  packages/components/base/source/content-box/ContentBoxProps.ts
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/teaser-box/TeaserBoxProps.ts
  packages/components/base/source/teaser-row/TeaserRowProps.ts
  packages/components/base/source/teaser/TeaserProps.ts
  packages/components/blog/source/post-aside/PostAsideComponent.tsx
  packages/components/blog/source/post-aside/PostAsideProps.ts
  packages/components/blog/source/post-aside/typing.ts
  packages/components/blog/source/post-head/PostHeadProps.ts
  packages/components/blog/source/post-share-bar/PostShareBarProps.ts
  packages/components/blog/source/post-teaser/PostTeaserProps.ts
  packages/components/blog/source/shared/NewsItemProps.ts
  packages/components/form/source/form-check-group/checkbox-group/CheckboxGroupProps.ts
  packages/components/form/source/form-check-group/radio-group/RadioGroupProps.ts
  packages/components/form/source/input/InputProps.ts
  packages/tools/bundler/bundle/bundleTs.ts
  packages/tools/bundler/package.json
  packages/tools/bundler/schema/schemaDereference.ts
  packages/tools/bundler/schema/schemaToTypescript.ts
  yarn.lock
Labels: enhancement, minor

#1522 Pass all arguments to debounced function
  packages/components/core/source/utils/debounce.js
Labels: patch

#1526 Add button group component
  packages/components/base/source/button-group/ButtonGroupComponent.tsx
  packages/components/base/source/button-group/ButtonGroupProps.ts
  packages/components/base/source/button-group/_button-group-vars.scss
  packages/components/base/source/button-group/_container.scss
  packages/components/base/source/button-group/button-group.schema.json
  packages/components/base/source/button-group/button-group.scss
  packages/components/base/source/button-group/index.ts
  packages/components/base/source/button-group/typing.ts
Labels: minor

#1523 Restructure section props
  package.json
  packages/components/base/source/section/SectionComponent.tsx
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/section/section.schema.json
  packages/components/base/source/section/section.scss
  packages/tools/bundler/bundle/scss.ts
Labels: major

#1405 Reactivate storybook component-tokens addon
  packages/tools/storybook/package.json
  yarn.lock
Labels: dependencies, patch, internal

#1527 Add button group to section
  packages/components/base/source/button-group/ButtonGroupComponent.tsx
  packages/components/base/source/button-group/ButtonGroupProps.ts
  packages/components/base/source/button-group/button-group.schema.json
  packages/components/base/source/section/SectionComponent.tsx
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/section/_section-vars.scss
  packages/components/base/source/section/section.schema.json
  packages/components/base/source/section/section.scss
Labels: minor

#1529 Feature/accesibility improvements
  packages/components/base/source/image/lightbox-image/LightboxImageComponent.tsx
Labels: enhancement, patch

#1528 Remove glide from bundle
  packages/tools/bundler/bundle/rollupUtils.ts
  packages/tools/bundler/bundle/scss.ts
Labels: patch

#1387 Simplify Collapsible Box Transition
  packages/components/base/source/collapsible-box/CollapsibleBox.js
  packages/components/base/source/collapsible-box/CollapsibleBoxComponent.tsx
  packages/components/base/source/collapsible-box/collapsible-box.scss
  packages/components/core/source/utils/index.ts
  packages/components/core/source/utils/slide.js
  packages/components/core/source/utils/window.js
Labels: major

#1548 Fix token create import
  .vscode/settings.json
  packages/components/base/source/collapsible-box/CollapsibleBox.js
  packages/components/core/source/storybook/helpers.ts
  packages/tools/style-dictionary/writeTokens.js
Labels: patch
