Repository kickstartDS/kickstartDS, pull requests merged in 2023-10, with the labels that each got.

#1496 Update all peerDependencies
  packages/components/base/package.json
  packages/components/blog/package.json
  packages/components/core/package.json
  packages/components/form/package.json
  yarn.lock
Labels: patch

#1497 Cache generated js files for monorepo build / chromatic
  .circleci/config.yml
Labels: bug, skip-release

#1486 Section content alignment
  .vscode/settings.json
  packages/components/base/source/headline/headline.scss
  packages/components/base/source/section/SectionComponent.tsx
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/section/section.schema.json
  packages/components/base/source/section/section.scss
  packages/components/core/source/storybook/helpers.ts
Labels: major

#1516 Bring back `hidden` attribute on icon sprite component
  packages/tools/style-dictionary/formats/html/icon-sprite.js
Labels: patch

#1517 Remove content prop from Section component
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/section/section.schema.json
Labels: patch
