Repository kickstartDS/kickstartDS, pull requests merged in 2023-05, with the labels that each got.

#1292 Upgrade to Storybook 7
  .circleci/config.yml
  .nvmrc
  .vscode/launch.json
  package.json
  packages/components/base/package.json
  packages/components/base/source/global/_rich-text-vars.scss
  packages/components/base/source/global/_rich-text.scss
  packages/components/base/source/global/base.scss
  packages/components/base/source/rich-text/RichTextComponent.tsx
  packages/components/base/source/rich-text/rich-text.scss
  packages/components/base/source/section/SectionComponent.tsx
  packages/components/base/source/text-media/TextMediaComponent.tsx
  packages/components/blog/package.json
  packages/components/blog/source/post-head/PostHeadComponent.tsx
  packages/components/core/package.json
  packages/components/core/source/design-tokens/border-radius.mdx
  packages/components/core/source/design-tokens/border-radius.stories.mdx
  packages/components/core/source/design-tokens/box-shadow.mdx
  packages/components/core/source/design-tokens/box-shadow.stories.mdx
  packages/components/core/source/design-tokens/colors.mdx
  packages/components/core/source/design-tokens/icons.mdx
  packages/components/core/source/design-tokens/spacing.mdx
  packages/components/core/source/design-tokens/spacing.stories.mdx
  packages/components/core/source/design-tokens/typography.mdx
  packages/components/form/package.json
  packages/tools/bundler/.storybook/main.js
  packages/tools/bundler/.storybook/main.ts
  packages/tools/bundler/.storybook/preview.ts
  packages/tools/bundler/bundle/rollupUtils.js
  packages/tools/bundler/package.json
  packages/tools/bundler/stories/createStoriesFromMarkdown.js
  packages/tools/bundler/stories/createStory.js
  packages/tools/docusaurus/docs/concepts/index.mdx
  packages/tools/docusaurus/docs/foundations/components/react.md
  packages/tools/docusaurus/docs/guides/create/components.mdx
  packages/tools/docusaurus/docs/guides/create/storybook.mdx
  packages/tools/docusaurus/docs/guides/use-our-starter.mdx
  packages/tools/docusaurus/package.json
  packages/tools/storybook/.gitignore
  packages/tools/storybook/.storybook/main.js
  packages/tools/storybook/.storybook/main.ts
  packages/tools/storybook/.storybook/preview.js
  packages/tools/storybook/.storybook/preview.ts
  packages/tools/storybook/index.js
  packages/tools/storybook/package.json
  patches/storybook-design-token+3.0.0-beta.2.patch
  yarn.lock
Labels: minor

#1319 Update design token addon beta
  packages/components/core/package.json
  packages/tools/storybook/package.json
  yarn.lock
Labels: dependencies, patch

#1320 Always add trailing slashes in docs
  packages/tools/docusaurus/docusaurus.config.js
Labels: bug, documentation

#1333 Remove section gutter when option is set to `none`
  packages/components/base/source/section/_section-vars.scss
Labels: patch
