Repository kickstartDS/kickstartDS, pull requests merged in 2024-01, with the labels that each got.

#1573 Fix `Select Field` schema: `icon` property set to `object`, should be `string`
  packages/components/form/source/form-field/select-field/SelectFieldProps.ts
  packages/components/form/source/form-field/select-field/select-field.schema.json
Labels: bug, patch

#1550 Add section mode `slider`
  packages/components/base/source/section/Section.js
  packages/components/base/source/section/SectionComponent.tsx
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/section/SectionSlider.js
  packages/components/base/source/section/_section-vars.scss
  packages/components/base/source/section/index.ts
  packages/components/base/source/section/section.schema.json
  packages/components/base/source/section/section.scss
Labels: minor

#1586 Add `tileWidth` Prop to section
  packages/components/base/source/section/SectionComponent.tsx
  packages/components/base/source/section/SectionProps.ts
  packages/components/base/source/section/_section-vars.scss
  packages/components/base/source/section/section.schema.json
  packages/components/base/source/section/section.scss
Labels: minor

#1595 Fix hidden icons in storybook
  packages/tools/style-dictionary/formats/storybook/icons.js
Labels: patch
