Repository kickstartDS/kickstartDS, pull requests merged in 2024-04, with the labels that each got.

#1636 Upgrade storybook
  packages/components/base/package.json
  packages/tools/bundler/.storybook/main.ts
  packages/tools/bundler/.storybook/preview.ts
  packages/tools/bundler/package.json
  packages/tools/storybook/package.json
  packages/tools/storybook/vite.config.ts
  patches/@kickstartds+jsonschema-utils+2.8.0.patch
  yarn.lock
Labels: documentation

#1641 Next to Master
  package.json
  packages/components/base/package.json
  packages/components/blog/package.json
  packages/components/core/package.json
  packages/components/form/package.json
  packages/tools/bundler/.storybook/main.ts
  packages/tools/bundler/.storybook/preview.ts
  packages/tools/bundler/package.json
  packages/tools/storybook/package.json
  packages/tools/storybook/vite.config.ts
  patches/@kickstartds+jsonschema-utils+2.8.0.patch
  yarn.lock
Labels: documentation

#1642 Add `color` & `file` to text-field's type prop
  packages/components/form/source/form-field/text-field/TextFieldProps.ts
  packages/components/form/source/form-field/text-field/text-field.schema.json
Labels: patch

#1643 Add types for window._ks
  packages/components/core/package.json
  packages/components/core/source/core/domLoaded.ts
  packages/components/core/source/core/index.ts
  packages/components/core/source/core/radio.js
  packages/components/core/source/core/radio.ts
  yarn.lock
Labels: patch

#1645 Enable version branch
  .autorc
Labels: internal

#1646 Add `open` prop to collapsible box
  packages/components/base/source/collapsible-box/CollapsibleBoxComponent.tsx
  packages/components/base/source/collapsible-box/CollapsibleBoxProps.ts
  packages/components/base/source/collapsible-box/collapsible-box.schema.json
  packages/components/base/source/section/SectionProps.ts
Labels: minor
