Repository kickstartDS/kickstartDS, pull requests merged in 2024-10, with the labels that each got.

#1700 Remove obsolete polyfills
  packages/components/base/package.json
  packages/components/base/source/generic/polyfills/_focus-visible.scss
  packages/components/base/source/generic/polyfills/polyfills.js
  packages/components/base/source/global/base.js
  packages/components/base/source/global/base.scss
  packages/components/base/source/helpers/svg-icon-baseurl.js
  packages/components/form/source/form-check/form-check.scss
  packages/components/form/source/form-field/form-field.scss
  yarn.lock
Labels: patch

#1701 [Snyk] Security upgrade markdown-to-jsx from 7.3.2 to 7.4.0
  packages/components/base/package.json
  yarn.lock
Labels: dependencies

#1704 Use `section` element for section component
  packages/components/base/source/section/SectionComponent.tsx
Labels: minor
